#!/bin/bash

if [ "$1" == "install" ]; then
	cmds="up down logs scale ps"
	for c in $cmds; do
		sudo ln -s /usr/local/bin/dc /usr/local/bin/${c}
	done
	echo "dc: $cmds commands installed!"
	exit 0
fi

if [ ! -e docker-compose.yml ];  then
	echo "docker-compose.yml not found!" >&2
	exit 1
fi

labels=$(cat docker-compose.yml | grep "com.docker.compose.project")

if [ $(echo $labels | wc -l) -ne 1 ]; then
	echo "Found more than one com.docker.compose.project in docker-compose.yml!" >&2
	exit 1
fi

cmd=
if [ $0 != "dc" ]; then
	cmd=$(basename $0)
fi

docker-compose -p ${labels/*=/} $cmd $@
#WARNING: Found orphan containers

