#!/bin/bash

if [ "$1" == "install" ]; then
	cmds="up down logs scale ps"
	for c in $cmds; do
		sudo ln -s /usr/local/bin/dc /usr/local/bin/${c}
	done
	echo "dc: $cmds commands installed!"
	exit 0
fi

file=
if [ ! -e docker-compose.yml ];  then
	file="-f -"
fi

labels=$(cat docker-compose.yml | grep "com.docker.compose.project")
project=
if [ $(echo $labels | wc -l) -ne 1 ]; then
	project="-p ${labels/*=/}"
fi

cmd=
if [ $(basename $0) == "dc" ]; then
	shift
	cmd=$1
	shift
else
	cmd=$(basename $0)
fi

docker-compose $file $project $cmd $@

